// flow-typed signature: 68fe3f0b6862c10d948ef81aaf9fec66
// flow-typed version: <<STUB>>/async-busboy_v^0.3.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-busboy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-busboy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-busboy/examples/index' {
  declare module.exports: any;
}

declare module 'async-busboy/specs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-busboy/examples/index.js' {
  declare module.exports: $Exports<'async-busboy/examples/index'>;
}
declare module 'async-busboy/index' {
  declare module.exports: $Exports<'async-busboy'>;
}
declare module 'async-busboy/index.js' {
  declare module.exports: $Exports<'async-busboy'>;
}
declare module 'async-busboy/specs.js' {
  declare module.exports: $Exports<'async-busboy/specs'>;
}
