// flow-typed signature: 01fc15e9b752ee54a361ddbd995a5484
// flow-typed version: <<STUB>>/clarify_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clarify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'clarify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clarify/clarify' {
  declare module.exports: any;
}

declare module 'clarify/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clarify/clarify.js' {
  declare module.exports: $Exports<'clarify/clarify'>;
}
declare module 'clarify/test.js' {
  declare module.exports: $Exports<'clarify/test'>;
}
