// flow-typed signature: a848b05a09c6d9e9074225ccc7c7da1e
// flow-typed version: <<STUB>>/import-dir_vlatest/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'import-dir/test/index' {
  declare module.exports: any;
}

declare module 'import-dir/test/modules/moduleA' {
  declare module.exports: any;
}

declare module 'import-dir/test/modules/moduleB' {
  declare module.exports: any;
}

declare module 'import-dir/test/modules/moduleC' {
  declare module.exports: any;
}

// Filename aliases
declare module 'import-dir/index' {
  declare module.exports: $Exports<'import-dir'>;
}
declare module 'import-dir/index.js' {
  declare module.exports: $Exports<'import-dir'>;
}
declare module 'import-dir/test/index.js' {
  declare module.exports: $Exports<'import-dir/test/index'>;
}
declare module 'import-dir/test/modules/moduleA.js' {
  declare module.exports: $Exports<'import-dir/test/modules/moduleA'>;
}
declare module 'import-dir/test/modules/moduleB.js' {
  declare module.exports: $Exports<'import-dir/test/modules/moduleB'>;
}
declare module 'import-dir/test/modules/moduleC.js' {
  declare module.exports: $Exports<'import-dir/test/modules/moduleC'>;
}
