// flow-typed signature: 6a49d3f115f694f4478701237df7a4e2
// flow-typed version: <<STUB>>/koa-views_v^5.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-views'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-views' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-views/lib/index' {
  declare module.exports: any;
}

declare module 'koa-views/src/index' {
  declare module.exports: any;
}

declare module 'koa-views/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-views/lib/index.js' {
  declare module.exports: $Exports<'koa-views/lib/index'>;
}
declare module 'koa-views/src/index.js' {
  declare module.exports: $Exports<'koa-views/src/index'>;
}
declare module 'koa-views/test/index.js' {
  declare module.exports: $Exports<'koa-views/test/index'>;
}
