// flow-typed signature: afe364c20b98a3c25a43f94c59c73c37
// flow-typed version: <<STUB>>/koa-logger_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-logger/index' {
  declare module.exports: $Exports<'koa-logger'>;
}
declare module 'koa-logger/index.js' {
  declare module.exports: $Exports<'koa-logger'>;
}
