// flow-typed signature: 70a739609c2d803011511fd024b18c89
// flow-typed version: <<STUB>>/koa-webpack-middleware_v^1.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-webpack-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-webpack-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-webpack-middleware/lib/devMiddleware' {
  declare module.exports: any;
}

declare module 'koa-webpack-middleware/lib/hotMiddleware' {
  declare module.exports: any;
}

declare module 'koa-webpack-middleware/lib/index' {
  declare module.exports: any;
}

declare module 'koa-webpack-middleware/middleware/devMiddleware' {
  declare module.exports: any;
}

declare module 'koa-webpack-middleware/middleware/hotMiddleware' {
  declare module.exports: any;
}

declare module 'koa-webpack-middleware/middleware/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-webpack-middleware/lib/devMiddleware.js' {
  declare module.exports: $Exports<'koa-webpack-middleware/lib/devMiddleware'>;
}
declare module 'koa-webpack-middleware/lib/hotMiddleware.js' {
  declare module.exports: $Exports<'koa-webpack-middleware/lib/hotMiddleware'>;
}
declare module 'koa-webpack-middleware/lib/index.js' {
  declare module.exports: $Exports<'koa-webpack-middleware/lib/index'>;
}
declare module 'koa-webpack-middleware/middleware/devMiddleware.js' {
  declare module.exports: $Exports<'koa-webpack-middleware/middleware/devMiddleware'>;
}
declare module 'koa-webpack-middleware/middleware/hotMiddleware.js' {
  declare module.exports: $Exports<'koa-webpack-middleware/middleware/hotMiddleware'>;
}
declare module 'koa-webpack-middleware/middleware/index.js' {
  declare module.exports: $Exports<'koa-webpack-middleware/middleware/index'>;
}
