// flow-typed signature: a0e8bf67cd95bcfd8cc656501b513798
// flow-typed version: <<STUB>>/koa-session-mongoose_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-session-mongoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-session-mongoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-session-mongoose/test/index' {
  declare module.exports: any;
}

declare module 'koa-session-mongoose/test/session-store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-session-mongoose/index' {
  declare module.exports: $Exports<'koa-session-mongoose'>;
}
declare module 'koa-session-mongoose/index.js' {
  declare module.exports: $Exports<'koa-session-mongoose'>;
}
declare module 'koa-session-mongoose/test/index.js' {
  declare module.exports: $Exports<'koa-session-mongoose/test/index'>;
}
declare module 'koa-session-mongoose/test/session-store.js' {
  declare module.exports: $Exports<'koa-session-mongoose/test/session-store'>;
}
