// flow-typed signature: a64762e86b561c4c6b4019a93d19c68f
// flow-typed version: <<STUB>>/resolve-url_v^0.2.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resolve-url/resolve-url' {
  declare module.exports: any;
}

declare module 'resolve-url/test/resolve-url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resolve-url/resolve-url.js' {
  declare module.exports: $Exports<'resolve-url/resolve-url'>;
}
declare module 'resolve-url/test/resolve-url.js' {
  declare module.exports: $Exports<'resolve-url/test/resolve-url'>;
}
