// flow-typed signature: 0d4dc42bf181b2c61228df43bbc56e48
// flow-typed version: <<STUB>>/stack-chain_v^1.3.7/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stack-chain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stack-chain' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stack-chain/benchmark' {
  declare module.exports: any;
}

declare module 'stack-chain/format' {
  declare module.exports: any;
}

declare module 'stack-chain/stack-chain' {
  declare module.exports: any;
}

declare module 'stack-chain/test/produce' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/callSite-function' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/callSite-property' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/conflict-format-delayed-circular' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/conflict-format-delayed' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/conflict-format-existing' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/conflict-version-first' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/conflict-version-match' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/conflict-version-mismatch' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/extend' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/filter' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/format-replace' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/format-tostring-non-generic' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/non-extensible-errors' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/order' {
  declare module.exports: any;
}

declare module 'stack-chain/test/simple/uglify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stack-chain/benchmark.js' {
  declare module.exports: $Exports<'stack-chain/benchmark'>;
}
declare module 'stack-chain/format.js' {
  declare module.exports: $Exports<'stack-chain/format'>;
}
declare module 'stack-chain/index' {
  declare module.exports: $Exports<'stack-chain'>;
}
declare module 'stack-chain/index.js' {
  declare module.exports: $Exports<'stack-chain'>;
}
declare module 'stack-chain/stack-chain.js' {
  declare module.exports: $Exports<'stack-chain/stack-chain'>;
}
declare module 'stack-chain/test/produce.js' {
  declare module.exports: $Exports<'stack-chain/test/produce'>;
}
declare module 'stack-chain/test/simple/callSite-function.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/callSite-function'>;
}
declare module 'stack-chain/test/simple/callSite-property.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/callSite-property'>;
}
declare module 'stack-chain/test/simple/conflict-format-delayed-circular.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/conflict-format-delayed-circular'>;
}
declare module 'stack-chain/test/simple/conflict-format-delayed.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/conflict-format-delayed'>;
}
declare module 'stack-chain/test/simple/conflict-format-existing.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/conflict-format-existing'>;
}
declare module 'stack-chain/test/simple/conflict-version-first.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/conflict-version-first'>;
}
declare module 'stack-chain/test/simple/conflict-version-match.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/conflict-version-match'>;
}
declare module 'stack-chain/test/simple/conflict-version-mismatch.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/conflict-version-mismatch'>;
}
declare module 'stack-chain/test/simple/extend.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/extend'>;
}
declare module 'stack-chain/test/simple/filter.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/filter'>;
}
declare module 'stack-chain/test/simple/format-replace.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/format-replace'>;
}
declare module 'stack-chain/test/simple/format-tostring-non-generic.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/format-tostring-non-generic'>;
}
declare module 'stack-chain/test/simple/non-extensible-errors.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/non-extensible-errors'>;
}
declare module 'stack-chain/test/simple/order.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/order'>;
}
declare module 'stack-chain/test/simple/uglify.js' {
  declare module.exports: $Exports<'stack-chain/test/simple/uglify'>;
}
