// flow-typed signature: 6433968a4881d940848088f2b13eb0f3
// flow-typed version: <<STUB>>/trace_v^2.3.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'trace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trace/benchmark' {
  declare module.exports: any;
}

declare module 'trace/benchmark/memory-readstream' {
  declare module.exports: any;
}

declare module 'trace/benchmark/memory' {
  declare module.exports: any;
}

declare module 'trace/benchmark/time-fsaccess' {
  declare module.exports: any;
}

declare module 'trace/benchmark/time-setimmediate' {
  declare module.exports: any;
}

declare module 'trace/benchmark/time' {
  declare module.exports: any;
}

declare module 'trace/example' {
  declare module.exports: any;
}

declare module 'trace/test/scripts/regression-delayed-formater' {
  declare module.exports: any;
}

declare module 'trace/test/scripts/regression-http-close' {
  declare module.exports: any;
}

declare module 'trace/test/scripts/regression-net-connect' {
  declare module.exports: any;
}

declare module 'trace/test/scripts/regression-net-socket' {
  declare module.exports: any;
}

declare module 'trace/test/scripts/regression-timer-clear' {
  declare module.exports: any;
}

declare module 'trace/test/scripts/simple-fs-read' {
  declare module.exports: any;
}

declare module 'trace/test/scripts/simple-next-tick' {
  declare module.exports: any;
}

declare module 'trace/test/scripts/simple-timer' {
  declare module.exports: any;
}

declare module 'trace/test/test' {
  declare module.exports: any;
}

declare module 'trace/trace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trace/benchmark.js' {
  declare module.exports: $Exports<'trace/benchmark'>;
}
declare module 'trace/benchmark/memory-readstream.js' {
  declare module.exports: $Exports<'trace/benchmark/memory-readstream'>;
}
declare module 'trace/benchmark/memory.js' {
  declare module.exports: $Exports<'trace/benchmark/memory'>;
}
declare module 'trace/benchmark/time-fsaccess.js' {
  declare module.exports: $Exports<'trace/benchmark/time-fsaccess'>;
}
declare module 'trace/benchmark/time-setimmediate.js' {
  declare module.exports: $Exports<'trace/benchmark/time-setimmediate'>;
}
declare module 'trace/benchmark/time.js' {
  declare module.exports: $Exports<'trace/benchmark/time'>;
}
declare module 'trace/example.js' {
  declare module.exports: $Exports<'trace/example'>;
}
declare module 'trace/test/scripts/regression-delayed-formater.js' {
  declare module.exports: $Exports<'trace/test/scripts/regression-delayed-formater'>;
}
declare module 'trace/test/scripts/regression-http-close.js' {
  declare module.exports: $Exports<'trace/test/scripts/regression-http-close'>;
}
declare module 'trace/test/scripts/regression-net-connect.js' {
  declare module.exports: $Exports<'trace/test/scripts/regression-net-connect'>;
}
declare module 'trace/test/scripts/regression-net-socket.js' {
  declare module.exports: $Exports<'trace/test/scripts/regression-net-socket'>;
}
declare module 'trace/test/scripts/regression-timer-clear.js' {
  declare module.exports: $Exports<'trace/test/scripts/regression-timer-clear'>;
}
declare module 'trace/test/scripts/simple-fs-read.js' {
  declare module.exports: $Exports<'trace/test/scripts/simple-fs-read'>;
}
declare module 'trace/test/scripts/simple-next-tick.js' {
  declare module.exports: $Exports<'trace/test/scripts/simple-next-tick'>;
}
declare module 'trace/test/scripts/simple-timer.js' {
  declare module.exports: $Exports<'trace/test/scripts/simple-timer'>;
}
declare module 'trace/test/test.js' {
  declare module.exports: $Exports<'trace/test/test'>;
}
declare module 'trace/trace.js' {
  declare module.exports: $Exports<'trace/trace'>;
}
